In [28]:
#!pip install modern_robotics
import modern_robotics as mr
from modern_robotics import *
import numpy as np
import math
from math import cos,sin

### Forward Kinematics

The URRPR spatial open chain of Figure is shown in its zero position. Determine the end-effector zero position configuration M, the screw axes $\mathscr{S}{i}$ in {0}, and the screw axes $\mathscr{B}{i}$ in {b}.

<img src="./assets/URRPR.png" width="500"/>

$$
M=\left[\begin{array}{cccc}
1 & 0 & 0 & (2+\sqrt{3}) L \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & (1+\sqrt{3}) L \\
0 & 0 & 0 & 1
\end{array}\right]
$$


the screw axes Si​ in {0} 
$$
\begin{array}{l|l|l}
i & w_i & V_i \\
\hline 1 & (0,0,1) & (0,-L, 0) \\
\hline 2 & (0,1,0) & (0,0, L) \\
\hline 3 & (0,1,0) & (L, 0,(1+\sqrt{3}) L) \\
\hline 4 & (0,1,0) & ((1-\sqrt{3}) L, 0,(2+\sqrt{3}) L) \\
\hline 5 & (0,0,0) & (0,0,1) \\
\hline 6 & (0,0,1) & (0,-(2+\sqrt{3}) L, 0) \\
\hline
\end{array}
$$



the screw axes Bi​ in {b} 
$$
\begin{array}{c|c|c}
i & \omega_i & V_i \\
\hline 1 & (0,0,1) & (0,(1+\sqrt{3}) L, 0) \\
\hline 2 & (0,1,0) & ((1+\sqrt{3}) L, 0,-(1+\sqrt{3}) L) \\
\hline 3 & (0,1,0) & ((2+\sqrt{3}) L, 0,-L) \\
\hline 4 & (0,1,0) & (2 L, 0,0) \\
\hline 5 & (0,0,0) & (0,0,1) \\
\hline 6 & (0,0,1) & (0,0,0)
\end{array}
$$


In [29]:
L = 1
M = np.array(
    [[1, 0, 0, (2+np.sqrt(3))*L],
     [0, 1, 0, 0],
        [0, 0, 1, (1+np.sqrt(3))*L],
        [0, 0, 0, 1]])

S1 = [0, 0, 1, 0, -L, 0]
S2 = [0, 1, 0, 0, 0, L]
S3 = [0, 1, 0, L, 0, (1+np.sqrt(3))*L]
S4 = [0, 1, 0, (1-np.sqrt(3))*L, 0, (2+np.sqrt(3))*L]
S5 = [0, 0, 0, 0, 0, 1]
S6 = [0, 0, 1, 0, -(2+np.sqrt(3))*L, 0]
PI = math.pi



th1 = -PI/2
th2 = PI/2
th3 = PI/3
th4 = -PI/4
th5 = 1
th6 = PI/6

Slist = np.array([S1, S2, S3, S4, S5, S6]).T
thetalist = np.array([th1, th2, th3,th4,th5,th6])
T07 = FKinSpace(M, Slist, thetalist)
print(T07)

[[ 5.00000000e-01  8.66025404e-01  1.07239309e-16  1.00000000e+00]
 [ 2.24143868e-01 -1.29409523e-01 -9.65925826e-01 -1.89777748e+00]
 [-8.36516304e-01  4.82962913e-01 -2.58819045e-01 -4.50850794e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


# Quiz Chapter 4, Forward Kinematics
<br/>
<br/>
**Question 1 Determine the end-effector zero configuration M.**

**[[1,0,0,3.732],[0,1,0,0],[0,0,1,2.732],[0,0,0,1]]**
<br/>

**Question 2 Determine the screw axes Si in {0} when the robot is in its zero position.**    

**[[0,0,0,0,0,0],[0,1,1,1,0,0],[1,0,0,0,0,1],[0,0,1,-0.732,0,0],[-1,0,0,0,0,-3.732],[0,1,2.732,3.732,1,0]]**
 
<br/>
**Question 3 Determine the screw axes Bi in {b} when the robot is in its zero position.**    

**[[0,0,0,0,0,0],[0,1,1,1,0,0],[1,0,0,0,0,1],[0,2.732,3.732,2,0,0],[2.732,0,0,0,0,0],[0,-2.732,-1,0,1,0]]**

<br/>
**Question 4 Use the function FKinSpace in the given software to find the end-effector configuration.**    

**[[0.5,0.87,0,1],[0.22,-0.13,-0.97,-1.9],[-0.84,0.48,-0.26,-4.5],[0,0,0,1]]**

<br/>
**Question 5 Use the function FKinBody in the given software to find the end-effector configuration.**    

**[[0.5,0.87,0,1],[0.22,-0.13,-0.97,-1.9],[-0.84,0.48,-0.26,-4.5],[0,0,0,1]]**

<br/>

In [30]:
import numpy as np 
import modern_robotics as mr 
import math

pi = math.pi

# question 1
M = np.array([[    1,    0,    0, 3.73],
              [    0,    1,    0,    0],
              [    0,    0,    1, 2.73],
              [    0,    0,    0,    1]])
print("\nQuestion 1:\n", np.array2string(M, separator=',', suppress_small=True))

# question 2
Slist = np.array([[    0,    0,    1,    0,   -1,    0],
                  [    0,    1,    0,    0,    0,    1],
                  [    0,    1,    0,    1,    0, 2.73],
                  [    0,    1,    0,-0.73,    0, 3.73],
                  [    0,    0,    0,    0,    0,    1],
                  [    0,    0,    1,    0,    -3.73,0]]).T
print("\nQuestion 2:\n", np.array2string(Slist, separator=',', suppress_small=True))

# question 3
Blist = np.array([[    0,    0,    1,    0, 2.73,    0],
                  [    0,    1,    0, 2.73,    0,-2.73],
                  [    0,    1,    0, 3.73,    0,   -1],
                  [    0,    1,    0,    2,    0,    0],
                  [    0,    0,    0,    0,    0,    1],
                  [    0,    0,    1,    0,    0,    0]]).T
print("\nQuestion 3:\n", np.array2string(Blist, separator=',', suppress_small=True))

# question 4
thetalist_space = np.array([-pi/2, pi/2, pi/3, -pi/4, 1, pi/6])
MatSpace = mr.FKinSpace(M, Slist, thetalist_space) 
MatSpaceOff = np.around(MatSpace, decimals=2)
print("\nQuestion 4:\n", np.array2string(MatSpaceOff, separator=',', suppress_small=True))

# question 5
thetalist_body = np.array([-pi/2, pi/2, pi/3, -pi/4, 1, pi/6])
MatBody = mr.FKinBody(M, Blist, thetalist_body)
MatBodyOff = np.around(MatBody, decimals=2)
print("\nQuestion 5:\n", np.array2string(MatBodyOff, separator=',', suppress_small=True))


Question 1:
 [[1.  ,0.  ,0.  ,3.73],
 [0.  ,1.  ,0.  ,0.  ],
 [0.  ,0.  ,1.  ,2.73],
 [0.  ,0.  ,0.  ,1.  ]]

Question 2:
 [[ 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
 [ 0.  , 1.  , 1.  , 1.  , 0.  , 0.  ],
 [ 1.  , 0.  , 0.  , 0.  , 0.  , 1.  ],
 [ 0.  , 0.  , 1.  ,-0.73, 0.  , 0.  ],
 [-1.  , 0.  , 0.  , 0.  , 0.  ,-3.73],
 [ 0.  , 1.  , 2.73, 3.73, 1.  , 0.  ]]

Question 3:
 [[ 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
 [ 0.  , 1.  , 1.  , 1.  , 0.  , 0.  ],
 [ 1.  , 0.  , 0.  , 0.  , 0.  , 1.  ],
 [ 0.  , 2.73, 3.73, 2.  , 0.  , 0.  ],
 [ 2.73, 0.  , 0.  , 0.  , 0.  , 0.  ],
 [ 0.  ,-2.73,-1.  , 0.  , 1.  , 0.  ]]

Question 4:
 [[ 0.5 , 0.87, 0.  , 1.  ],
 [ 0.22,-0.13,-0.97,-1.9 ],
 [-0.84, 0.48,-0.26,-4.5 ],
 [ 0.  , 0.  , 0.  , 1.  ]]

Question 5:
 [[ 0.5 , 0.87, 0.  , 1.  ],
 [ 0.22,-0.13,-0.97,-1.9 ],
 [-0.84, 0.48,-0.26,-4.5 ],
 [ 0.  , 0.  , 0.  , 1.  ]]
